apiVersion: apps/v1
kind: Deployment
metadata:
  name: student1
  labels:
    app: student1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: student1
  template:
    metadata:
      labels:
        app: student1
    spec:
      containers:
      - name: student1
        image: syedmj/v1:student1 
      
