apiVersion: v1
kind: Service
metadata:
  name: jbossservice1
  labels:
    app: app
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort:
    - name: mgmt
      port: 9990
      targetPort: 9990
  selector:
      app: app
      
